language: ruby
rvm:
  - 2.2.3
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
addons:
  ssh_known_hosts: cbracco.me
before_install:
  - nvm install 0.12
  - npm i -g npm@2
  - openssl aes-256-cbc -K $encrypted_8205f213b679_key -iv $encrypted_8205f213b679_iv -in deploy-key.enc -out deploy-key -d
install:
  - bundle install
  - npm install
before_script:
  - echo -e "Host cbracco.me\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n" >> ~/.ssh/config
script:
  - npm run build:production
  - npm run test:scripts
  - npm run test:html
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy-key
  - ssh-add $TRAVIS_BUILD_DIR/deploy-key
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
