language: ruby
rvm:
  - 2.3.0
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
before_install:
  - nvm install 8.11.3
  - npm i -g npm@5
install:
  - bundle install
  - npm install
script:
  - npm run build-production
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./build/production
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
