language: ruby
rvm:
  - 2.2.3
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
addons:
  ssh_known_hosts: cbracco.me
cache:
  bundler: true
  directories:
    - node_modules
before_install:
  - nvm install 0.12
  - npm i -g npm@2
install:
  - npm install
before_script:
  - echo -e "Host cbracco.me\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config
script:
  - npm run build:production
  - npm run test:scripts
  - npm run test:html
before_deploy:
  - openssl aes-256-cbc -K $encrypted_8205f213b679_key -iv $encrypted_8205f213b679_iv
    -in deploy-key.enc -out id_rsa -d && chmod 600 id_rsa;
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
