language: ruby

rvm:
  - 2.3.1

# speeds up installation of html-proofer
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

# route your build to the container-based infrastructure for a faster build
sudo: false

# cache both Ruby gems and npm node_modules between builds (for faster builds)
cache:
  bundler: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - bundle install
  - npm install

script:
  - npm run travis

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then npm run deploy; fi
