#
# Configuration
#

# Site
title: "Chris Bracco"
title_after: "web designer, engineer, etc."
description: "Hello! My name is Chris and I am a web designer and engineer who cares about user-centered design, performance, and accessibility."
descriptionShort: "web designer, engineer, etc."
author: "Chris Bracco"
encoding: "utf-8"
language: "en-us"

# Routes
source: ./source
destination: ./build
baseurl: ""
url: "http://localhost:9999"
root: /
permalink: /:categories/:title/

# Writing
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  work:
    output: false
    permalink: /work/:title/

# Publishing
future: true
show_drafts: true

# <head>
favicons: true
openGraph: true
twitterCards:
  username: cbracco

# Analytics
analytics:
  id: UA-12953082-11
  domain: {{ site.url }}

# 3rd-Party
codepen:
  username: cbracco
  url: https://codepen.io/cbracco

ello:
  username: cbracco
  url: https://ello.co/cbracco

github:
  username: cbracco
  url: https://github.com/cbracco

goodreads:
  username: cbracco
  url: https://www.goodreads.com/cbracco

instagram:
  username: cbracco
  url: https://www.instagram.com/cbracco

instapaper:
  username: cbracco
  url: https://www.instapaper.com/p/cbracco

runkeeper:
  username: cbracco
  url: https://runkeeper.com/user/cbracco/profile

speakerdeck:
  username: cbracco
  url: https://speakerdeck.com/cbracco

spotify:
  username: cbracco
  url: https://open.spotify.com/user/cbracco

twitter:
  username: cbracco
  url: https://twitter.com/cbracco

# Referral URLs
referralUrls:
  linode: https://cbrac.co/linode_ref
  namecheap: https://cbrac.co/namecheap_ref
  dropbox: https://cbrac.co/mydropbox_ref

# Excludes
#
# Travis-CI bundles all gems in the vendor directory on its build
# servers, which Jekyll will mistakenly read and explode on.
exclude: [vendor]
